sudo: required
services:
  - docker
  - elasticsearch
env:
  global:
    - IMAGE_NAME=ibmcase/bluecompute-catalog-test

before_script:
  - docker pull "$IMAGE_NAME" || true

script:
  - docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .

after_success:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${TRAVIS_JOB_NUMBER}"
  on:
    branch: master

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TRAVIS_JOB_NUMBER}"

deploy:
  - docker run "${IMAGE_NAME}:${TRAVIS_JOB_NUMBER}"
  - docker run --name=catalog -p 8081:8081 -e ELASTICSEARCH_URI="http://127.0.0.1:9200" "${IMAGE_NAME}:${TRAVIS_JOB_NUMBER}"
  - curl http://127.0.0.1:8081/micro/items

after_deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${TRAVIS_JOB_NUMBER}"
  on:
    branch: master

after_script:
  - docker images