sudo: required
dist: xenial
language: java
jdk:
  - openjdk8
env:
  global:
    - IMAGE_NAME=catalog-mp
    - TAG=travis
    - RELEASE_NAME=catalog
    - INVENTORY_RELEASE=inventory
stages:
  - local build and test
jobs:
  include:
    - stage: local build and test
      services:
      - elasticsearch
      - mysql
      - docker
      env:
      - elasticsearch_url=http://localhost:9201
      - inventory_health=http://localhost:9081/inventory/health
      - zipkinHost=localhost
      - zipkinPort=9411
      before_script:
      # Startup RabbitMQ
      - docker run -d --name rabbitmq rabbitmq
      # Setup elastic search
      - docker pull ibmcase/bluecompute-elasticsearch
      - docker run -d -p 9201:9200 --name elasticsearch ibmcase/bluecompute-elasticsearch #9200 seems arbitrarily taken in Travis
      # Pull and run inventorydb
      - docker pull ibmcase/bc-inventorydb:v2.0.0
      - docker run -p 9041:3306 -d --name inventorydb -e MYSQL_ROOT_PASSWORD=password ibmcase/bc-inventorydb:v2.0.0
      # Export vars
      - export GATEWAY=$(docker network inspect bridge | grep "Gateway" | awk '/"/{print $2}' | sed -e 's/^"//' -e 's/"$//')
      - export RABBIT_HOST=$(docker inspect -f "{{ .NetworkSettings.IPAddress }}" rabbitmq)
      # Run Inventory and start it w/ vars
      - docker pull ibmcase/inventory-mp:v2.0.0
      - docker run -d --name inventory -p 9444:9443 -p 9081:9080 -e zipkinHost=${zipkinHost} -e zipkinPort=${zipkinPort} -e jdbcURL=jdbc:mysql://${GATEWAY}:9041/inventorydb?useSSL=false -e dbuser=root -e dbpassword=password -e rabbit=${RABBIT_HOST} ibmcase/inventory-mp:v2.0.0
      # Set mpRestClient URL
      - echo "-Dclient.InventoryServiceClient/mp-rest/url=http://localhost:9081/inventory/rest/inventory/" >> src/main/liberty/config/jvm.options
      - echo "-Delasticsearch_url=http://localhost:9201" >> src/main/liberty/config/jvm.options
      - echo "-Dinventory_health=http://localhost:9081/health" >> src/main/liberty/config/jvm.options
      script:
      - mvn clean install
      - mvn liberty:start-server -DtestServerHttpPort=9082
      - sleep 25
      # Run Catalog API Test
      - curl http://localhost:9081/inventory/rest/inventory
      - curl http://localhost:9082/health
      - bash scripts/api_tests.sh
    - stage: kubernetes build, deploy, and test
      services:
      - docker
      env:
      - CHANGE_MINIKUBE_NONE_USER=true
      install:
      # Install minikube and helm
      - curl -O https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/microprofile/utility_scripts/install_minikube_and_helm.sh
      - chmod +x install_minikube_and_helm.sh
      - bash install_minikube_and_helm.sh
      before_script:
      # Add helm repos for bluecompute services
      - helm repo add bc-inventory https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-micro-inventory/microprofile/chart/release
      # Run inventory
      - helm install --set travis.external=true,travis.releaseName=${INVENTORY_RELEASE},rabbitmq.enabled=true --name inventory bc-inventory/inventory
      # Setup ElasticSearch
      - helm install --set clustername=catalog --name es ./chart/ibmcase-elasticsearch
      - MINIKUBE_IP=$(minikube ip)
      script:
      # Maven Build
      - mvn clean install
      # Build Docker image
      - docker build -t "${IMAGE_NAME}:${TAG}" .
      # Install Catalog
      - helm install --set travis=true --set image.repository=${IMAGE_NAME},image.tag=${TAG} --name ${RELEASE_NAME} ./chart/catalog/
      # Wait for Catalog to be ready
      - kubectl get deployments ${RELEASE_NAME}-catalog -o yaml
      - READY=$(kubectl get deployments ${RELEASE_NAME}-catalog -o yaml | grep "readyReplicas" | awk '{print $2}')
      - echo $READY
      - until [ -n "$READY" ] && [ ${READY} -ge 1 ]; do READY=$(kubectl get deployments ${RELEASE_NAME}-catalog -o yaml | grep "readyReplicas" | awk '{print $2}'); kubectl get deployments -o wide; echo "Waiting for catalog to be ready"; sleep 10; done
      # Wait for catalog deployment to start accepting connections
      - sleep 35
      # Run auth API Test
      - CATALOG_NODE_PORT=$(kubectl get service ${RELEASE_NAME}-catalog -o=jsonpath='{.spec.ports[0].nodePort}')
      - bash scripts/api_tests.sh $MINIKUBE_IP $CATALOG_NODE_PORT
