apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ toYaml .Values.labels | indent 4 -}}
    release: {{.Release.Name | quote }}
    chart: "{{ .Release.Name }}-{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
type: Opaque
data:
  binding: {{ cat `{"uri": "http://` .Release.Name `-` .Values.service.name `:9200/" }` | nospace | b64enc | quote }}
