dependencies:
  - name: elasticsearch
    version: 1.4.0
    repository: http://storage.googleapis.com/kubernetes-charts-incubator
    condition: elasticsearch.enabled
  - name: inventory
    version: 0.5.0
    repository: https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/spring/docs/charts
    condition: inventory.enabled
