replicaCount: 1

image:
  repository: ibmcase/bluecompute-catalog
  pullPolicy: Always
  tag: 0.5.0

service:
  name: catalog
  type: NodePort
  externalPort: 8081
  internalPort: 8081

ingress:
  enabled: false
  hostname: catalog.bluecompute.com
  path: /micro/items

tls:
  enabled: false
  secretName:
  crt: ENTER_BASE64_ENCODED_CERTIFICATE
  key: ENTER_BASE64_ENCODED_KEY

# Alpine with cURL
curl:
  image: alexeiled/curl
  imageTag: latest
  imagePullPolicy: IfNotPresent

# Included Community MySQL Chart.
# - Even if disabled, these fields are used to provide information
#   for external MySQL deployments.
# - Also, the MySQL docker image is used in load_data.yaml to load
#   MySQL deployment (internal or not) with some static inventory data
catalogelasticsearch:
  enabled: true
  # If chart is not enabled, this field can be used as external elasticsearch host
  fullnameOverride: bluecompute-catalog-elasticsearch
  protocol: http
  port: 9200
  username:
  password:
  healthcheck: "_cat/health"
  cacertificatebase64:
  appVersion: 6.3.1
  image: 
    repository: docker.elastic.co/elasticsearch/elasticsearch-oss
    tag: 6.3.1
    pullPolicy: IfNotPresent
  client:
    replicas: 1
    serviceType: ClusterIP
  master:
    replicas: 2
    persistence:
      enabled: false
  data:
    replicas: 1
    persistence:
      enabled: false

# Inventory Microservice URL, which is needed to pull data into Elasticsearch
inventory:
  enabled: true
  url: http://bluecompute-inventory:8080

resources:
  limits:
    memory: 384Mi
  requests:
    memory: 64Mi