replicaCount: 1

image:
  repository: ibmcase/bluecompute-catalog
  pullPolicy: Always
  tag: latest

service:
  name: catalog
  type: ClusterIP
  externalPort: 8081
  internalPort: 8081

ingress:
  enabled: false
  hostname: catalog.bluecompute.com
  path: /micro/items

tls:
  enabled: false
  secretName:
  crt: ENTER_BASE64_ENCODED_CERTIFICATE
  key: ENTER_BASE64_ENCODED_KEY

dataloader:
  image:
    repository: ibmcase/bluecompute-dataloader
    tag: latest

inventory:
  service:
    url:

catalogelasticsearch:
  secretName: binding-catalog-elasticsearch

resources:
  limits:
    memory: 128Mi
  requests:
    memory: 64Mi
