replicaCount: 1

image:
  repository: ibmcase/bluecompute-catalog
  tag: 0.5.0
  pullPolicy: Always

service:
  type: ClusterIP
  externalPort: 8081
  internalPort: 8081
  nodePort: 31381

ingress:
  enabled: false
  hostname: catalog.bluecompute.com
  path: /micro/items
  ibmCloud:
    redirectToHTTPS: false

tls:
  enabled: false
  secretName:
  crt: ENTER_BASE64_ENCODED_CERTIFICATE
  key: ENTER_BASE64_ENCODED_KEY

# Alpine with cURL
curl:
  image: alexeiled/curl
  imageTag: latest
  imagePullPolicy: IfNotPresent

elasticsearch:
  enabled: true
  protocol: http
  host: catalog-elasticsearch-client
  port: 9200
  username:
  password:
  healthcheck: "_cat/health"
  cacertificatebase64:

# Inventory Microservice URL, which is needed to pull data into Elasticsearch
inventory:
  url:

resources:
  limits:
    memory: 384Mi
  requests:
    memory: 64Mi