apiVersion: v1
kind: Secret
metadata:
  name: binding-catalog-elasticsearch
  namespace: default
type: Opaque
data:
  # {"uri":"http://elastic:changeme@127.0.0.1:9200/"}
  binding: "eyJ1cmkiOiJodHRwOi8vZWxhc3RpYzpjaGFuZ2VtZUAxMjcuMC4wLjE6OTIwMC8ifQo="