apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-config
data:
  jvm.options: |
    -Dclient.InventoryServiceClient/mp-rest/url=http://{{ .Release.Name }}-inventory:9080/inventory/rest/inventory
