apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "catalog.fullname" . }}
  labels:
    {{- include "catalog.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        {{- include "catalog.labels" . | indent 8 }}
    spec:
      initContainers:
      {{- include "catalog.elasticsearch.initcontainer" . | indent 6 }}
      {{- include "catalog.inventory.initcontainer" . | indent 6 }}
      containers:
      - name: catalog
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          protocol: TCP
        env:
        {{- include "catalog.environmentvariables" . | indent 8 }}
        {{- include "catalog.elasticsearch.environmentvariables" . | indent 8 }}
        - name: INVENTORY_URL
          value: {{ template "catalog.inventory" . }}
        resources:
{{ toYaml .Values.resources | indent 10 }}