{{- if and (not .Values.elasticsearch.enabled) .Values.elasticsearch.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "catalog.fullname" . }}-elasticsearch-secret
  labels:
    {{- include "catalog.labels" . | indent 4 }}
type: Opaque
data:
  elasticsearch-password: {{ .Values.elasticsearch.password | b64enc | quote }}
  elasticsearch-ca-certificate: {{ .Values.elasticsearch.cacertificatebase64 | b64enc | quote }}
{{- end }}