{{- if and (not .Values.catalogelasticsearch.enabled) .Values.catalogelasticsearch.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.catalogelasticsearch.fullnameOverride }}
  labels:
    {{- include "catalog.labels" . | indent 4 }}
type: Opaque
data:
  elasticsearch-password: {{ .Values.catalogelasticsearch.password | b64enc | quote }}
  elasticsearch-ca-certificate: {{ .Values.catalogelasticsearch.cacertificatebase64 | b64enc | quote }}
{{- end }}