apiVersion: v1
kind: Service
metadata:
  annotations:
    bluecompute: "true"
    #prometheus.io/scrape: "true"
  name: {{ .Release.Name }}-{{ .Values.service.name }}
  labels:
    {{- include "catalog.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.servicePort }}
  - name: https
    port: {{ .Values.service.servicePortHttps }}
  selector:
    {{- include "catalog.labels" . | indent 4 }}